name: build default on ubuntu gcc

on:
  repository_dispatch:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '0 */2 * * *'

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install git cmake make gcc ccache
      - name: update submodule
        run: |
          git submodule update --init --recursive
      - name: configure cmake
        run: |
            cmake -B ${{github.workspace}}/build \
                  -D CMAKE_INSTALL_PREFIX=${{github.workspace}}/build/install \
                  -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
                  -D CMAKE_C_COMPILER=/usr/lib/ccache/gcc
      - name: make
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: install
        working-directory: ${{github.workspace}}/build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -- install
